Temporarily comment out GitHub workflows

diff --git a/.github/workflows/im-build.yml b/.github/workflows/im-build.yml
--- a/.github/workflows/im-build.yml
+++ b/.github/workflows/im-build.yml
@@ -5,52 +5,52 @@ on:
   pull_request:
 
 jobs:
-  unit-tests:
-    runs-on: ubuntu-latest
+  # unit-tests:
+  #   runs-on: ubuntu-latest
 
-    services:
-      # Label used to access the service container
-      postgres:
-        image: postgres:11
-        # Provide the password for postgres
-        env:
-          POSTGRES_USER: postgres
-          POSTGRES_PASSWORD: postgres
-        options: >-
-          --health-cmd pg_isready
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 5
-        ports:
-          - 5432:5432
-    env:
-      TESTMODEL_PATH: intermine-demo
-    strategy:
-      fail-fast: true
-      matrix:
-        testSuite: [intermine, bio]
-    steps:
-    - uses: actions/checkout@v4
-    - name: Set up JDK 11
-      uses: actions/setup-java@v1
-      with:
-        java-version: '11'
-    - name: Set up python 3.10
-      uses: actions/setup-python@v5
-      with:
-        python-version: '3.10'
-    - name: Install PostgreSQL client
-      run: |
-        set -euo pipefail
-        sudo apt-get update -y
-        sudo apt-get install -y libpq-dev postgresql-client
-    - name: Run unit tests
-      run: |
-        set -euo pipefail
-        mkdir -p ${HOME}/.gradle
-        cp config/ci/gradle.properties ${HOME}/.gradle
-        ./config/ci/init.sh ${GITHUB_WORKSPACE} $(which python3) ${{ matrix.testSuite }} none http://localhost:8080/intermine-demo
-        ./config/ci/run.sh ${GITHUB_WORKSPACE} $(which python3) ${{ matrix.testSuite }} none http://localhost:8080/intermine-demo
+  #   services:
+  #     # Label used to access the service container
+  #     postgres:
+  #       image: postgres:11
+  #       # Provide the password for postgres
+  #       env:
+  #         POSTGRES_USER: postgres
+  #         POSTGRES_PASSWORD: postgres
+  #       options: >-
+  #         --health-cmd pg_isready
+  #         --health-interval 10s
+  #         --health-timeout 5s
+  #         --health-retries 5
+  #       ports:
+  #         - 5432:5432
+  #   env:
+  #     TESTMODEL_PATH: intermine-demo
+  #   strategy:
+  #     fail-fast: true
+  #     matrix:
+  #       testSuite: [intermine, bio]
+  #   steps:
+  #   - uses: actions/checkout@v4
+  #   - name: Set up JDK 11
+  #     uses: actions/setup-java@v1
+  #     with:
+  #       java-version: '11'
+  #   - name: Set up python 3.10
+  #     uses: actions/setup-python@v5
+  #     with:
+  #       python-version: '3.10'
+  #   - name: Install PostgreSQL client
+  #     run: |
+  #       set -euo pipefail
+  #       sudo apt-get update -y
+  #       sudo apt-get install -y libpq-dev postgresql-client
+  #   - name: Run unit tests
+  #     run: |
+  #       set -euo pipefail
+  #       mkdir -p ${HOME}/.gradle
+  #       cp config/ci/gradle.properties ${HOME}/.gradle
+  #       ./config/ci/init.sh ${GITHUB_WORKSPACE} $(which python3) ${{ matrix.testSuite }} none http://localhost:8080/intermine-demo
+  #       ./config/ci/run.sh ${GITHUB_WORKSPACE} $(which python3) ${{ matrix.testSuite }} none http://localhost:8080/intermine-demo
 
   ws-tests:
     runs-on: ubuntu-latest
@@ -75,7 +75,8 @@ jobs:
     strategy:
       fail-fast: true
       matrix:
-        client: [JS, PY]
+        # client: [JS, PY]
+        client: [PY]
     steps:
     - uses: actions/checkout@v4
     - name: Set up JDK 11
